namespace: moreati
name: uv
version: 0.0.3
description: |-
  Drop in replacement for Ansible's pip module, using Astral uv

authors:
  - Alex Willmer <alex@moreati.org.uk>

license:
  - GPL-3.0-or-later

readme: README.md
repository: http://github.com/moreati/ansible-uv
issues: http://github.com/moreati/ansible-uv/issues

build_ignore:
  - .DS_Store
  - .ansible-lint
  - .git
  - .gitignore
  - .tox
  - .venv
  - ansible.cfg
  - bootstrap*.yml
  - galaxy.yml
  - issue*.yml
  - ruff.toml
  - tox.ini
  - uv_install.sh

  - "*.py[cdo]"
  - "*.retry"
  - "*.tar.gz"

tags:
  - astral
  - pip
  - uv
  - venv
  - virtualenv
